on: [ push, pull_request ]
name: CodeStyle

jobs:
    code-style-tests:
        name: "Style Checks"
        runs-on: "ubuntu-latest"
        continue-on-error: ${{ matrix.allow-fail }}
        strategy:
            matrix:
                include:
                    # - { php-version: 7.4, dependencies: locked, coverage: none, with_coverage: false, allow-fail: false }
                    - { php-version: 7.4, dependencies: highest, coverage: none, with_coverage: false, allow-fail: true }
                    # - { php-version: 8.0, dependencies: locked, coverage: none, with_coverage: false, allow-fail: false }
                    # - { php-version: 8.0, dependencies: highest, coverage: none, with_coverage: false, allow-fail: true }
                    - { php-version: 8.0, dependencies: locked, coverage: none, with_coverage: false, allow-fail: false }
                    # - { php-version: 8.1, dependencies: highest, coverage: none, with_coverage: false, allow-fail: true }

        steps:
            -   name: "Checkout code"
                uses: "actions/checkout@v2"

            -   name: "Install PHP"
                uses: "shivammathur/setup-php@v2"
                with:
                    coverage: "${{ matrix.coverage }}"
                    ini-values: display_errors=On, display_startup_errors=On, error_reporting=32767
                    php-version: "${{ matrix.php-version }}"

            -   name: "Install dependencies with Composer"
                uses: "ramsey/composer-install@v2"
                with:
                    dependency-versions: "${{ matrix.dependencies }}"

            -   name: "Run Grump checks"
                run: |
                    vendor/bin/codecept build -c .
                    vendor/bin/grumphp run -c .

